### ISSUE TITLE
Not compatible with VS Code 1.70.2?

### ISSUE THREAD

**Issue by joba-1** [mcu-debug/peripheral-viewer#21]
Type: Bug Report

**Describe the bug**
- OS and Version: linux (latest tumbleweed)
- VS Code Version: 1.70.2
- Extension Version: 1.4.6
- Target Device: raspberry pico
- Other extensions you installed (and if the issue persists after disabling them): basics for c++, cmake, jupyter, platformio, python (13)
- A clear and concise description of what the bug is.
I have not disabled all extensions, since the message clearly says what the problem is: extension is incompatible with vs code version 1.70.2.

**To Reproduce**
Steps to reproduce the behavior: just try to install the extension...
![image](https://github.com/mcu-debug/peripheral-viewer/assets/32450554/22cb72cb-9d1b-4563-a40c-d3d0e350d600)

**Expected behavior**
extension installs

**Comment by joba-1** [comment]
Context: I'd like to use the Cortex-Debug extension to debug a raspberry pico, but installation depends on this one :(

**Comment by joba-1** [comment]
fwiw: I downloaded the 1.4.6 release vsix, unzipped it, changed the required version in the manifest zipped the vsix again and installed it. So far, debugging seems to work...  :)

**Comment by MatthijsReyers** [comment]
I have exactly this issue as well, I simply upgraded my vscode installation to the lastest version, but if there is no reason for the extension to force versions `"^1.75.0"` it might be worth downgrading it?

**Comment by joba-1** [comment]
all available releases have the same minimum requirement.

But I must admit, the real problem for me was that the repository refresh was turned off for the vs code repo.
Now it is on and I am at code v1.82.2. All good :)
