### ISSUE TITLE
Pscd parser does not support processors without a Dname property

### ISSUE THREAD

**Issue by marcowidmer** [mcu-debug/peripheral-viewer#6]
Type: Bug Report

**Describe the bug**
- OS and Version: Debian GNU/Linux 11 (bullseye)
- VS Code Version: 1.76.2
- Extension Version: 1.4.3
- Target Device: STM32H723VGTx
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.
The `<processor>` tags in the [STM32H723VGTx psdc file](https://pack-asset-service.keil.arm.com/Keil/STM32H7xx_DFP/3.0.0/Keil.STM32H7xx_DFP.pdsc) do not have a `Dname="..."` property. This causes them to be discarded by the psdc parser. Since there are zero processors found, none are shown in the selection dropdown and I am unable to select one to download the .svd.

**Expected behavior**
The extension should work correctly with processors without a Dname property.

**Code sample and logs**
- `launch.json`
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug",
			"type": "cortex-debug",
			"request": "launch",
			"executable": "...",

			"svdPath": "Keil::STM32H7xx_DFP@3.0.0",
			"deviceName": "STM32H723VGTx",
		}
	]
}
```

**Screenshots**
![Screenshot from 2023-03-21 14-06-20](https://user-images.githubusercontent.com/3530185/226615224-b8e2b41e-7800-4156-b9c9-8638e90886b1.png)

**Comment by thegecko** [comment]
Thanks @marcowidmer , will investigate this.

cc @jreineckearm
